Print@"OK, so we are going to analyse the Kalb-Ramond theory now. The first step is to load the Hamilcar package.";
<<xAct`Hamilcar`;
Print@"The next step is to disable the dynamical metric, since we are working on Minkowski spacetime.";
$DynamicalMetric=False;
Print@"When we work with Poisson brackets, we smear the operands manually.";
$ManualSmearing=True;
Print@"Next, we need to define a bunch of things based on what we've been told. Firstly we will define the constant symbols in the theory.";
DefConstantSymbol[CouplingConstant750dbd1c];
Print@"Next we define the canonical fields in the theory. Note that the conjugate momenta are defined automatically alongside the fields.";
DefCanonicalField[CanonicalFielda5962efc[-a,-b],Antisymmetric[{-a,-b}]];
DefCanonicalField[CanonicalField640262b4[-a]];
Print@"Next we define the multipliers in the theory.";
DefTensor[LagrangeMultipliera5962efc[-a,-b],M3,Antisymmetric[{-a,-b}]];
DefTensor[LagrangeMultiplier640262b4[-a],M3];
Print@"Now we want to define two smearing functions for each of the canonical fields, whose index structure matches those fields.";
DefTensor[SmearingOnea5962efc[-a,-b],M3,Antisymmetric[{-a,-b}]];
DefTensor[SmearingOne640262b4[-a],M3];
DefTensor[SmearingTwoa5962efc[-a,-b],M3,Antisymmetric[{-a,-b}]];
DefTensor[SmearingTwo640262b4[-a],M3];
Print@"Now we define the total Hamiltonian density for the theory.";
TotalHamiltonianDensity=-1/8*(ConjugateMomentumCanonicalFielda5962efc[-a, -b]*ConjugateMomentumCanonicalFielda5962efc[a, b])/CouplingConstant750dbd1c + ConjugateMomentumCanonicalField640262b4[-a]*LagrangeMultiplier640262b4[a] + 2*ConjugateMomentumCanonicalFielda5962efc[-a, -b]*CD[b][CanonicalField640262b4[a]] + 4*CouplingConstant750dbd1c*CD[-b][CanonicalFielda5962efc[-a, -c]]*CD[c][CanonicalFielda5962efc[a, b]] - 2*CouplingConstant750dbd1c*CD[-c][CanonicalFielda5962efc[-a, -b]]*CD[c][CanonicalFielda5962efc[a, b]];
TotalHamiltonianDensity//=Recanonicalize;
TotalHamiltonianDensity//Print;
Print@"The first step is to find all the primary constraints. Having been provided with the total Hamiltonian density, we could recover these by reading them off directly. It is safer, however, to proceed systematically, by taking variations with respect to the multipliers.";
Expr=VarD[LagrangeMultipliera5962efc[-a,-b],CD][TotalHamiltonianDensity];
Expr//=Recanonicalize;
Expr//Print;
Print@"So that is zero, and hence no primary constraint from this field. Now let's check the other one.";
Expr=VarD[LagrangeMultiplier640262b4[-a],CD][TotalHamiltonianDensity];
Expr//=Recanonicalize;
Expr//Print;
Print@"Ah, so that is non-zero, and hence there are three primary constraints associated with that multiplier. Let's define a tensor to represent that those constraints.";
DefTensor[PrimaryConstraint640262b4[a],M3];
FromPrimaryConstraint640262b4=MakeRule[{PrimaryConstraint640262b4[a],Evaluate@Expr},MetricOn->All,ContractMetrics->True];
FromPrimaryConstraint640262b4//PrependTotalFrom;
Print@"So, the theory has three primary constraints in total. Now we need to check whether these constraints are preserved in time. We smear them with appropriate smearing functions before taking Poisson brackets with the total Hamiltonian. To compute the secondaries as (potentially indexed) tensor expressions, we then take variations with respect to the smearing functions.";
Expr=PoissonBracket[SmearingOne640262b4[-a]*PrimaryConstraint640262b4[a],TotalHamiltonianDensity];
Expr//=VarD[SmearingOne640262b4[-a],CD][#]&;
Expr//=Recanonicalize;
Expr//Print;
Print@"Ah, so the velocities of these primaries don't vanish identically, nor is it equal to a combination of any other constraints (there are none), nor is it equal to an expression which can be set to zero for appropriate values of the multipliers. Hence we have found some secondary constraints. Specifically, we have found two secondary constraints, because the expression is the spatial divergence of a two-form in three dimensions, which is the curl of a vector (i.e. the vector to which the two-form is dual). let's define a tensor to represent those secondary constraints.";
DefTensor[SecondaryConstraint640262b4[a],M3];
FromSecondaryConstraint640262b4=MakeRule[{SecondaryConstraint640262b4[a],Evaluate@Expr},MetricOn->All,ContractMetrics->True];
FromSecondaryConstraint640262b4//PrependTotalFrom;
Print@"We now need to check whether the secondaries are preserved in time. We proceed as before, smearing with an appropriate smearing function and taking the Poisson bracket with the total Hamiltonian, before taking variations with respect to the smearing function to recover the indexed tensor expression.";
Expr=PoissonBracket[SmearingOne640262b4[-a]*SecondaryConstraint640262b4[a],TotalHamiltonianDensity];
Expr//=VarD[SmearingOne640262b4[-a],CD][#]&;
Expr//=Recanonicalize;
Expr//Print;
Print@"Ah, so the velocities of the secondaries vanish identically, and hence there are no further constraints, and we have found all the constraints in the theory. Now we need to classify the constraints into first and second class. To do this, we need to compute the Poisson brackets between all pairs of constraints.";
Expr=PoissonBracket[SmearingOne640262b4[-a]*PrimaryConstraint640262b4[a],SmearingTwo640262b4[-a]*SecondaryConstraint640262b4[a]];
Expr//Print;
Print@"Ah, so the Poisson bracket between the primaries and secondaries is vanishing. This means that both constraints are first class. We have now found and classified all the constraints in the theory. To summarise, the theory has five constraints in total: three primary and two secondary. Both constraints are first class. The total number of canonical degrees of freedom in the theory is 2*(3+3), where the 2 is from the field-momentum pairs, and the (3+3) is from the three-dimensional vector and three-dimensional two-form components of the four-dimensional two-form field. From this we subtract 2*3 degrees of freedom for the primary first class constraints, and another 2*2 degrees of freedom for the secondary first-class constraint, leaving us with 2*(3+3)-2*3-2*2=2 canonical degrees of freedom, or equivalently 1 physical degrees of freedom.";
Quit[];
